# Generated by Django 6.0.3 on 2026-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at_project_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
