# Generated by Django 6.0.3 on 2026-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detailed_scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
