# Generated by Django 6.0.3 on 2026-04-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_detailed_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, choices=[('Tanzania', 'Tanzania'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('DRC', 'Democratic Republic of the Congo'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('South Africa', 'South Africa'), ('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('Angola', 'Angola'), ('Namibia', 'Namibia'), ('Botswana', 'Botswana'), ('Zimbabwe', 'Zimbabwe'), ('Other', 'Other/Global')], help_text='Select the country where this project took place.', max_length=100, null=True),
        ),
    ]
