# Generated by Django 6.0.3 on 2026-04-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_herocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='intro_statement',
            field=models.TextField(default="Unlocking the potential of mining projects with <span class='text-gold'>unparalleled expertise</span> and relentless innovation. Pejuni is your strategic partner in subsurface risk management."),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='why_choose_us_intro',
            field=models.TextField(default='When you choose Pejuni, you are selecting a trusted partner that combines specialized expertise, advanced technologies, and an unwavering commitment to safety. We increase the net value of your open-pit or underground project through innovative engineering solutions.'),
        ),
    ]
