# Generated by Django 6.0.3 on 2026-04-08 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_herocontent_intro_statement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_description', models.TextField(default='Engineering stability. Ensuring operational excellence. Pejuni Resources.')),
                ('address_hq', models.TextField(default='Mwanza, Tanzania')),
                ('phone_hq', models.CharField(default='+255 759 199 623', max_length=50)),
                ('phone_aus', models.CharField(default='+61 470 578 151', max_length=50)),
                ('email_primary', models.EmailField(default='admin@pejuni.com', max_length=254)),
                ('email_secondary', models.EmailField(default='info@pejuni.com', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
