# Generated by Django 6.0.3 on 2026-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_created_at_teammember_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
