# Generated by Django 6.0.3 on 2026-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammember_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='cv',
            field=models.FileField(blank=True, help_text="Upload the member's CV (PDF recommended)", null=True, upload_to='team_cvs/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Full professional biography for the detail profile.', null=True),
        ),
    ]
