# Generated by Django 6.0.3 on 2026-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_created_at_service_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
